config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  get '/', to: 'users#index', as: 'home'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :increment_post_comments_counter
  after_destroy :decrement_post_comments_counter

  private

  def decrement_post_comments_counter
    post.decrement!(:comments_counter)
  end

  def increment_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :increment_post_likes_counter
  after_destroy :decrement_post_likes_counter

  private

  def increment_post_likes_counter
    post.increment!(:likes_counter)
  end

  def decrement_post_likes_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_default_comments_counter, on: :create
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  after_create :increment_user_posts_counter
  after_destroy :decrement_user_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def decrement_user_posts_counter
    author.decrement!(:posts_counter)
  end

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end

  def set_default_comments_counter
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :set_default_posts_counter, on: :create
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def set_default_posts_counter
    self.posts_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def new
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    # pp @post
    # @comment = @post.comments.new(comment_params)
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    @user = User.find(params[:user_id])

    if @comment.save
      flash[:notice] = 'Comment created successfully.'
      redirect_to user_post_path(@user, @post)
    else
      puts "Comment not saved. Errors: #{comment.errors.full_messages}" # Add this line for debugging
      render 'new'
    end
  end

  private

  def find_user
    @user = current_user
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    # like = post.likes.build(user: current_user)
    like = Like.new(user: current_user, post:)

    if like.save
      flash[:success] = 'Post liked!'
    else
      pp @like.errors
      flash[:error] = 'Error liking the post.'
    end
    redirect_to request.referer
  end
end

app/controllers/post_controller.rb
class PostsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  # Index action to list all posts
  def index
    @user = User.find(params[:user_id])
    # Preloads the comments and likes for each post to avoid N+1 queries
    @posts = @user.posts.includes(:comments,
                                  :likes).order(created_at: :desc).paginate(page: params[:page],
                                                                            per_page: 5)
  end

  # Show action to display a single post for a specific user
  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  # New action to display the post creation form
  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  # Create action to handle post creation
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.likes_counter = 0
    @post.comments_counter = 0
    if @post.save
      @user = User.find(params[:user_id])
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      pp @post.errors
      pp @post.errors.full_messages
      @user = User.find(params[:user_id])
      render 'new'
    end
  end

  # Edit action to display the post edit form
  def edit
    @post = Post.find(params[:id])
  end

  # Update action to handle post updates
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render 'edit'
    end
  end

  # Destroy action to delete a post
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # Index action to list all users
  def index
    @users = User.all
  end

  # Show action to display a single user's profile
  def show
    @user = User.find(params[:id])
  end

  # New action to display the user creation form
  def new
    @user = User.new
  end

  # Create action to handle user creation
  def create
    @user = User.new(user_params)
    @user.posts_counter = 0
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      pp @user.errors
      render 'new'
    end
  end

  # Edit action to display the user edit form
  def edit
    @user = User.find(params[:id])
  end

  # Update action to handle user updates
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render 'edit'
    end
  end

  # Destroy action to delete a user
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/new.html.erb
<div class='container'>
    <div class='card col-md-4'>
        <h1 class='card-header p-2 '>Add New Comment</h1>
        <%= form_for [@user, @post, @comment] do |f| %>
            <div class='card-body'>
                <div class="form-group">
                    <%= f.text_area :text, class: "form-control", placeholder: 'Add a comment...', rows: 3 %>
                </div>
            </div>
            <div class='card-footer'>
                <div class="actions">
                    <%= f.submit 'Post Comment', class: 'btn btn-primary'%>
                </div>
                <%= link_to 'Back', user_post_path(@user, @post) %>
            <div>
        <% end %>
    <div>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css"> %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/create.html.erb
<h2>Success</h2>
<div>
  Post created successfully
</div>

app/views/posts/edit.html.erb
<h2>Edit Post '<%= @post.title %>'</h2>
<%= form_for [@user, @post] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <%= f.submit 'Update Post' %>
<% end %>

app/views/posts/index.html.erb
<div class='container'>
    <h1>All Posts</h1>
    <div class='row mb-2 m-0 pt-2'>
        <div class='col-md-1'>
            <img src=<%= @user.photo %>
                class='img-thumbnail' />
        </div>
        <div class='col-md-11 card pt-2'>
            <div class='row justify-content-between'>
                <h4 class='align-bottom'><%= @user.name %></h4>
                <label class='align-bottom text-end'>Number of posts: <span><%= @user.posts_counter %></span></label>
            </div>
        </div>
        <div class='col-md-12 card mt-2'>
            <p><%= @user.bio %></p>
        </div>
    </div>
    <ul class='table table-responsive table-hover p-0'>
        <% @posts.each do |post| %>
            <li class=''>
                <div class='card mt-2'>
                    <h5 class='col-md-12'>
                        <%= link_to "#{post.title} by #{post.author.name}", user_post_path(@user, post) %>
                    </h5>
                    <p class='col-md-12 pt-2'>
                        <%= post.text %>
                    </p>
                    <div class='col-md-12 pt-2 text-end'>
                        <label class='me-2'>
                            Comments: <span><%= post.comments_counter %></span>
                        </label>
                        <label>
                            Likes: <span><%= post.likes_counter %></span>
                        </label>
                    </div>
                </div>
                <div class='col-md-12 card mt-2'>
                    <% post.recent_comments.each do |comment| %>
                        <div class=''>
                            <%= comment.user.name %></span>: <span><%= comment.text %></span>
                        </div>
                    <% end %>
                </div>
            </li>
        <% end %>
    </ul>
    <div class='d-flex justify-content-center'>
        <div class='col-md-4 text-center'>
            <%= will_paginate @posts, class: 'pagination' %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<h2>Create a New Post</h2>
<%= form_for [@user, @post] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <%= f.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<div class='container'>
    <h1>Post Details</h1>
    <div class='row card mt-2 mb-2 m-0 pt-2'>
        <h5 class='col-md-12'>
            <%= link_to "#{@post.title} by #{@post.author.name}", user_post_path(@user, @post) %>
        </h5>
        <div class='col-md-12 pt-2 text-end'>
            <label class='me-2'>
                Comments: <span><%= @post.comments_counter %></span>
            </label>
            <label>
                Likes: <span><%= @post.likes_counter %></span>
            </label>
        </div>
        <p class='col-md-12 pt-2'>
            <%= @post.text %>
        </p>
        <div class='d-flex pt-2 justify-content-end gap-2 mb-2'>
            <%= 
                button_to 'Like', user_post_likes_path(@user, @post), 
                method: :post, 
                data: {turbo_method: :create},
                class: 'btn btn-sm btn-primary'
            %>
            <%= 
                link_to 'New Comment',
                new_user_post_comment_path(@user, @post),
                class: 'btn btn-sm btn-primary'
            %>
        </div>
    </div>
    <div class='col-md-12 card mt-2 p-2'>
        <% @post.comments.each do |comment| %>
            <div >
                <%= comment.user.name %></span>: <span><%= comment.text %></span>
            </div>
        <% end %>
    </div>
</div>

app/views/users/create.html.erb
<h1>User Created</h1>
<p>Successfully created user: <%= @user.name %></p>
<%= link_to 'Back to All Users', users_path %>

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>
<%= form_for(@user) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>
  <div>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class='container'>
    <h1>All Users</h1>
    <ul class='table table-responsive table-hover p-0'>
        <% @users.each do |user| %>
            <li class='row mb-2 m-0'>
                <div class='col-md-1'>
                    <img src=<%= user.photo %>
                        class='img-thumbnail' />
                </div>
                <div class='col-md-11 card'>
                    <div class='row justify-content-between'>
                        <h4 class='align-bottom'><%= link_to user.name, user_path(user) %></h4>
                        <label class='align-bottom text-end'>Number of posts: <span><%= user.posts_counter %></span></label>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<h1>Create a New User</h1>
<%= form_for(@user) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>
  <div>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
  <%= f.submit 'Create User' %>
<% end %>

app/views/users/show.html.erb
<div class='container'>
    <h1 class='card-header p-2'>User Details</h1>
    <div class='row mb-2 m-0 pt-2'>
        <div class='col-md-1'>
            <img src=<%= @user.photo %>
                class='img-thumbnail' />
        </div>
        <div class='col-md-11 card pt-2'>
            <div class='row justify-content-between'>
                <h4 class='align-bottom'><%= @user.name %></h4>
                <label class='align-bottom text-end'>Number of posts: <span><%= @user.posts_counter %></span></label>
            </div>
        </div>
        <div class='col-md-12 card mt-2'>
            <p><%= @user.bio %></p>
        </div>
        <ul class='table table-responsive table-hover p-0'>
            <% @user.recent_posts.each do |post| %>
                <li class='card mt-2 p-2'>
                    <h5 class='col-md-12'>
                        <%= link_to post.title, user_post_path(@user, post) %>
                    </h5>
                    <p class='col-md-12 pt-2'>
                        <%= post.text %>
                    </p>
                    <div class='col-md-12 pt-2 text-end'>
                        <label class='me-2'>
                            Comments: <span><%= post.comments_counter %></span>
                        </label>
                        <label>
                            Likes: <span><%= post.likes_counter %></span>
                        </label>
                    </div>
                </li>
            <% end %>
        </ul>
        <div class='col-md-12 mt-2 text-center'>
            <a href=<%= user_posts_path(@user) %> class='btn btn-primary col-md-2'>See all Posts</a>
        </div>
    </div>
</div>